DATASETS:
  BURST:
    TRAINING:
      FPS: 30
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      MAX_NUM_INSTANCES: 4
    EVALUATION:
      SPLIT: val
  DAVIS:
    TRAINING:
      FPS: 30
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      MAX_NUM_INSTANCES: 4
    EVALUATION:
      SPLIT: val
  KITTI_STEP:
    TRAINING:
      FPS: 10
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      MAX_NUM_INSTANCES: 4
    EVALUATION:
      SPLIT: val
    MAX_INSTANCES_PER_CATEGORY: 1000
    NUM_CLASSES: 19
    THINGS_CLASSES: [11, 13]
    IGNORE_CLASSES: [255]
  VIPSEG:
    TRAINING:
      FPS: 5
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      MAX_NUM_INSTANCES: 4
    EVALUATION:
      SPLIT: val
    MAX_INSTANCES_PER_CATEGORY: 100
    IGNORE_CLASSES: [0]
MODEL:
  BACKBONE:
    FREEZE_AT: 2
    NAME: D2SwinTransformer
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  
  # path to pre-trained model weights
  WEIGHTS: "weights/dynamite_swin_large.pth"
  # (COCO) normalization mean and std (in RGB order)
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "DynamiteModel"
  SEM_SEG_HEAD:
    NAME: "DynamiteHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    # mask feature dimension
    MASK_DIM: 256
    NORM: "GN"
    REFINE_MASK_FEATURES: True
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    INTERACTIVE_TRANSFORMER_NAME: "DynamiteInteractiveTransformer"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"    
    # interactive transformer embedding dimension
    HIDDEN_DIM: 256
    # num of attention heads in multi-head attention
    NHEADS: 8
    # dropout in interactive transformer encoder layers
    DROPOUT: 0.0
    # feature dimension in encoder ffn
    DIM_FEEDFORWARD: 2048
    # whether to use pre-LayerNorm or not
    PRE_NORM: False
    # add input project 1x1 conv even if input channels and hidden dim is identical
    ENFORCE_INPUT_PROJ: False
    # some backbones require the input height and width to be divisible by a specific integer
    SIZE_DIVISIBILITY: 32
    # num of encoder layers; actually 9, add 1 for the loss on learnable query
    ENC_LAYERS: 10
    DECODER:
      # whether to use decoder in interactive transformer
      USE_DECODER: True
      # num of decoder layers
      DEC_LAYERS: 5
      # scaling factor for mask features before using in decoder
      DEC_SCALE_FACTOR: 1.0
    
    # positional encoding to be applied to multi-scale image features. 
    # Choose from ["spatial", "spatio_temporal"]
    KV_POSITIONAL_EMBED: "spatio_temporal"
    # positional encoding to be applied to click query descriptors. 
    # Choose from ["2D" for spatial, "3D" + frame index, "4D" + object ID, "5D" + click timestamp]
    Q_POSITIONAL_EMBED: "3D"
    # static background queries
    USE_STATIC_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9

    # whether to use no_click_query in learnable query initialization
    USE_NO_CLICK_QUERY: True
    # whether to use MLP projection head in learnable query initialization
    USE_MLP_FOR_QUERY_PROJ: False
    
    ## Loss parameters
    # whether loss calculation should include intermediate transformer encoder layer outputs (default: true)
    DEEP_SUPERVISION: true
    # mask loss weight
    MASK_WEIGHT: 5.0
    # dice loss weight
    DICE_WEIGHT: 5.0
    # num of points to sample, N in PointRend
    TRAIN_NUM_POINTS: 12544
    # oversampling ratio, k in PointRend
    OVERSAMPLE_RATIO: 3.0
    # importance sampling, beta in PointRend
    IMPORTANCE_SAMPLE_RATIO: 0.75

SOLVER:
  # number of samples in a batch across all GPUs, set it to 1 per GPU
  IMS_PER_BATCH: 1
  # num of training iterations on each GPU
  MAX_ITER: 100000
  # base learning rate
  BASE_LR: 0.0001
  # learning rate decay steps
  STEPS: (84000, 96000)
  
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 10000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

INPUT:
  AUGMENTATION:   # data augmentation parameters
    # color augmentation
    COLOR_AUG: true
    # random horizontal flip
    RANDOM_FLIP_AXIS: "horizontal"
    RANDOM_FLIP_PROB: 0.5
    # resize scale
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0
    IMAGE_SIZE: [512, 512]   # IMPORTANT: final frame dims must be divisible by MASK_FORMER.SIZE_DIVISIBILITY
  # use images in RGB order (note that cv2.imread loads images in BGR order)
  RGB: true

TRAINING:
  # enable pseudo-video pre-training
  PRETRAIN: false
  # pre-training datasets
  PRETRAIN_DATASET_LIST: [COCO]
  # proportion of training samples from each dataset
  PRETRAIN_DATASET_WEIGHTS: [1]
  # whether to apply deterministic augmentation in successive frames
  PRETRAIN_DETERMINISTIC_AUG: true
  
  # minimum object mask area permitted in training (n/a in pre-training)
  MIN_MASK_AREA: 400
  CLIP_LENGTH: 3
  # list of training datasets
  DATASET_LIST: [KITTI_STEP]
  # proportion of training sample from each dataset
  DATASET_WEIGHTS: [1]
  # resume or load (bool), specified by cmd line argument `--resume`
  RESUME:
  
  # save checkpoint every
  CHECKPOINT_SAVE_INTERVAL: 1600
  # #iters after which checkpoints will be regularly saved
  SAVE_CKPTS_AFTER: 0
  # max #checkpoints to keep on disk; older checkpoints are automatically deleted
  MAX_CKPTS_TO_KEEP: 2
  # run training with mixed precision
  AMP: false
  # gradients
  ACCUMULATE_GRADIENTS: true
  CLIP_GRADIENTS: false
  # run forward and backward passes with `torch.autograd.detect_anomaly`; useful for debugging only
  DETECT_ANOMALY: false
  # ignore OOMs, training skips to next iteration; only applies to single GPU training
  IGNORE_OOM_ERRORS: false
  # Learning rate
  BASE_LR: 0.0001
  LR_DECAY_RATES:
  - 0.0
  LR_DECAY_STEPS:
  - 0
  LR_WARMUP_ITERATIONS: 0
  # maximum number of batch samples to use per GPU
  MAX_SAMPLES_PER_GPU: 1
  # number of CPU workers to use for data-loading (per GPU process)
  NUM_CPU_WORKERS: -1
  # specifies the iteration interval for printing training metrics to console
  DISPLAY_INTERVAL: 5
  # specifies the iteration interval for saving metrics summary to tensorboard or Wandb
  SUMMARY_INTERVAL: 20

#TEST:
  #EVAL_PERIOD: 400000

DATALOADER:
  # num of dataloader workers
  NUM_WORKERS: 4
  ASPECT_RATIO_GROUPING: false # TODO
  #FILTER_EMPTY_ANNOTATIONS: True

ITERATIVE:
  TEST:
    MIN_MASK_AREA: 1
    INTERACTIVE_EVALAUTION: True
    # perform evaluation on specified datsets
    DATASETS: [KITTI_STEP]
    # refine a target until threshold is reached
    IOU_THRESHOLD: 0.95
    # Max no. of interactions allowed per target, in an entire sequence
    MAX_INTERACTIONS_PER_TARGET: 3
    # Max no. of corrective rounds
    MAX_ROUNDS: 3
    # save mask predictions
    SAVE_VISUALIZATIONS: false
    # Strategy to select the instance to add corrective clicks on. Choose between 'random', 'worst', 'best'
    EVAL_STRATEGY: "random"
    SINGLE_INSTANCE: false

CLICKER:
  TRAINING:
    # max #clicks *per-target object* to be sampled from a frame (default: 6)
    MAX_NUM_CLICKS_PER_INSTANCE: 6
    # prob of choosing optional frames to add foreground clicks in
    OPTIONAL_FRAMES_FG_SAMPLE_PROB: 0.2
    # probability of sampling background clicks from a frame (default: 0.)
    BACKGROUND_SAMPLING_PROB: 0.
    # probability scaling factor of sampling n no. of clicks (default: 0.7 )
    GAMMA: 0.7
    
    # max num of rounds during training
    MAX_NUM_REFINEMENT_ROUNDS: 3
    # max num of target objects to be refined in each training round
    MAX_NUM_INSTANCES_REFINED_PER_ROUND: 1
    # IoU threshold in training
    IOU_THRESHOLD: 0.95
    # which target objects are chosen during rounding. Choose between ["random", "worst"]
    REFINEMENT_STRATEGY: random

    
    
LOGGING:
  # Log level for the main process (rank 0)
  LOG_LEVEL: INFO
  # Log level for all subprocesses (rank >= 1)
  SUBPROCESS_LOG_LEVEL: WARN

WANDB:
  # whether to enable W&B logging (bool)
  ENABLE: false
  # name of the current run (str)
  RUN_NAME:
  # W&B account username (str)
  ENTITY:
  # W&B project name (str)
  PROJECT:
  # whether to monitor model parameter gradients (bool)
  WATCH_GRAD: false
  # training sweeps (bool)
  SWEEP: false

# path to experiment dir (str); overwritten by cmd line args
OUTPUT_DIR:
DEBUG: false
SEED: 2091831170
VERSION: 2